- name: Create mirror of China
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: Centos7-ustsc.repo.j2, dest: /etc/yum.repos.d/Centos7-ustsc-base.repo }
    - { src: Centos7-epel.repo.j2, dest: /etc/yum.repos.d/Centos7-epel.repo }
  
# - name: Replace epel url
  # shell: sed -e 's|^metalink=|#metalink=|g' -e 's|^#baseurl=https\?://download.fedoraproject.org/pub/epel/|baseurl=https://mirrors.ustc.edu.cn/epel/|g' -i.bak /etc/yum.repos.d/epel.repo
  
  register: replace_epel_url_output
